### ISSUE TITLE
cannot git clone your repo

### ISSUE THREAD

**Issue by condescendent** [AdminTurnedDevOps/PearsonCourses#2]
HI, I am a student/user from Oreilly training. I got the following error message when cloning your repo on a windows system using Git Bash. It looks like "GitOps-For-Kubernetes/test" has some reserved keyword. Could you rename this folder/file?

thanks. 

jyu3@QCOM-CIgWaGi8J9 CLANGARM64 ~/Repos
$ git clone git@github.com:AdminTurnedDevOps/PearsonCourses.git
Cloning into 'PearsonCourses'...
remote: Enumerating objects: 1908, done.
remote: Counting objects: 100% (413/413), done.
remote: Compressing objects: 100% (218/218), done.
remote: Total 1908 (delta 141), reused 320 (delta 134), pack-reused 1495
Receiving objects: 100% (1908/1908), 51.48 MiB | 16.05 MiB/s, done.
Resolving deltas: 100% (704/704), done.
error: invalid path 'GitOps-For-Kubernetes/test.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by wilberh** [comment]
@condescendent  - I have the same issue.  I ended up downloading the zip file of the repo and now able to access the "Kubernetes-Tooling-for-Platform-Engineering" folder.
![image](https://github.com/user-attachments/assets/30855fbf-dfd7-4765-81ba-9e7e253b98d1)

**Comment by AdminTurnedDevOps** [comment]
Hi - no need to clone the repo. The labs should be followed along in your environment.
